name: Makefile

on:
  workflow_dispatch:

env:
  RUNPOD_TOKEN: ${{ secrets.RUNPOD_DEV_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/pulumi/devcontainer:latest
      options: --user root
    permissions:
      contents: read
      packages: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        id: git
        with:
          submodules: "recursive"
      # - name: Print Secret Value
      #   run: echo secret value ${{ secrets.RUNPOD_DEV_TOKEN }} token
      - name: Unshallow clone for tags
        id: tags
        run: |
          sudo chown -R $(whoami) /__w/pulumi-runpod-native/pulumi-runpod-native
          git config --global --add safe.directory /__w/pulumi-runpod-native/pulumi-runpod-native
          git fetch --prune --unshallow --tags
      - name: Build
        id: build
        run: |
          make build
      - name: Install
        id: install
        run: |
          set -ex
          make install
      - name: PulumiUp
        id: up
        env:
          RUNPOD_TOKEN: a3e34a47a29c4afd9fbf8e287bcf571823a61f7748e71b38a973aee6bbf4de81ac829aebaca5ce88f90df736c6f557a4a38dcd97b6810ae26ece675a5d80d5b9
        run: make up
      - name: PulumiDown
        id: down
        run: make down
      - name: Generate multi-language examples from yaml IaC program
        id: examples
        run: |
          set -ex
          make gen_examples
